render:
  scale: 100 # æ¸²æŸ“ç²¾åº¦
query:
  others: true # å…è®¸æŸ¥è¯¢ä»–äººä¿¡æ¯
update:
  autoCheck: true # è‡ªåŠ¨æ£€æŸ¥æ›´æ–°
  cron: 0 0/10 * * * ? # æ›´æ–°æ£€æŸ¥æ—¶é—´
# éœ€è¦è°ƒç”¨è¿‡ğŸçš„æ¥å£code
mysCode:
  - 1034
  - 10035
# è‡ªå®šä¹‰ç»‘å®šè®¾å¤‡ä¸‹è½½url
url: https://ghproxy.mihomo.me/https://raw.githubusercontent.com/forchannot/get_device_info/main/app/build/outputs/apk/debug/app-debug.apk